[tox]
requires = tox-uv>=1
envlist = py312-django{42,52}, quality

[pycodestyle]
# error codes: http://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
# E501: line too long
# E731: do not assign a lambda expression, use a def
ignore = E501,E731

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    test
commands = pytest {posargs}

[testenv:py312-django42]
runner = uv-venv-lock-runner
dependency_groups =
    test
    django42
commands = pytest {posargs}

[testenv:py312-django52]
runner = uv-venv-lock-runner
dependency_groups =
    test
    django52
commands = pytest {posargs}

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
commands =
    pycodestyle src/i18n
    pylint --rcfile=pylintrc src/i18n
