[tox]
envlist = py312-django{42,52}, quality
requires = tox-uv>=1

[pycodestyle]
# error codes: http://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
# E501: line too long
# E731: do not assign a lambda expression, use a def
ignore = E501,E731

[testenv]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}
dependency_groups =
    django42: django42
    django52: test
allowlist_externals = make
commands =
    make test-python

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
allowlist_externals = make
commands =
    make quality-python
