name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'
  workflow_call:

jobs:
  run_tests:
    name: ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]
        toxenv: [quality, py-django42, py-django52]

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@d269b9917d8e33f7165632f15cc38a13726f64b5 # v9.0.0
        with:
          enable-cache: true
          python-version: "${{ matrix.python-version }}"

      - name: Install GNU gettext
        run: sudo apt install gettext

      - name: Install CI dependencies
        run: uv sync --group ci

      - name: Run tox
        run: uv run tox -e ${{ matrix.toxenv }}

      - name: Upload coverage to Codecov
        if: matrix.toxenv == 'py-django52' && matrix.python-version == '3.12'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
