name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'
jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
        - '3.12'
        toxenv: [quality, django42, django52]
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Python setup
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install GNU gettext
      run: sudo apt install gettext

    - name: Install Requirements
      run: |
        pip install -r requirements/pip.txt
        pip install -r requirements/ci.txt

    - name: Run Tests
      run: tox -e ${{ matrix.toxenv }}

    - name: Upload coverage to CodeCov
      if: matrix.python-version == '3.12' && matrix.toxenv == 'django42'
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
